
(()=>{
'use strict';
const DATA=Array.isArray(window.CHAAJAO_DATA)?window.CHAAJAO_DATA:[];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeHtml=html=>{const d=document.createElement('div');d.innerHTML=String(html||'');d.querySelectorAll('script,iframe,object,embed,style').forEach(x=>x.remove());d.querySelectorAll('*').forEach(el=>[...el.attributes].forEach(a=>{if(/^on/i.test(a.name))el.removeAttribute(a.name)}));return d.innerHTML};
const textOf=html=>{const d=document.createElement('div');d.innerHTML=String(html||'');return d.textContent||''};
const sourceInfo={chapter:{label:'Chapter Tests',count:149,desc:'Chapter wise tests karday aur mazboot.'},mock:{label:'Subject Mock Tests',count:191,desc:'Check karou poray subject ke mazbooti.'},grand:{label:'Grand Tests',count:8,desc:'Tayyari ka akhri step.'}};
let current='chapter', quiz=null;
const tests=src=>DATA.filter(t=>t.source===src);
const flat=t=>t.sections.flatMap(s=>s.questions.map(q=>({...q,section:s.name})))
const allQ=t=>flat(t).length;
const qCount=src=>tests(src).reduce((n,t)=>n+allQ(t),0);
const sourceColor=src=>src==='chapter'?'cyan':src==='mock'?'green':'gold';
function init(){document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showSection(b.dataset.section));$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');showSection('chapter');}
function showSection(src){current=src;$('#sidebar').classList.remove('open');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.section===src));$('#crumb').textContent=sourceInfo[src].label;$('#topStat').textContent=`${sourceInfo[src].count} tests • ${qCount(src).toLocaleString()} questions`;renderLibrary();window.scrollTo({top:0,behavior:'smooth'});}
function renderLibrary(){const list=tests(current);const subjects=[...new Set(list.map(t=>t.subject).filter(Boolean))].sort();$('#screen').innerHTML=`
<div class="hero"><div class="hero-panel"><div class="eyebrow">${sourceInfo[current].label}</div><h1>${sourceInfo[current].desc}</h1><p>${current==='chapter'?'Practice individual chapters across Physics, Math, English and Computer.':current==='mock'?'Work through complete subject-level mock papers across the collected dataset.':'Use the full-length and past-paper collection for final-stage practice.'}</p><div class="stats"><div class="stat"><b>${sourceInfo[current].count}</b><span>Tests</span></div><div class="stat"><b>${qCount(current).toLocaleString()}</b><span>Questions</span></div><div class="stat"><b>${subjects.length}</b><span>Subjects</span></div></div></div><div class="hero-panel quick-panel"><div class="eyebrow">Quick practice</div><div class="big">Random from this section</div><p>Start 20 answerable MCQs selected from the current section.</p><button class="btn" id="random20">Start 20 questions →</button></div></div>
<div class="section-head"><div><h2>Test Library</h2><div class="muted">Search by test name or filter by subject.</div></div></div>
<div class="toolbar"><input id="search" class="search" placeholder="Search tests…"><select id="subject" class="select"><option value="">All subjects</option>${subjects.map(s=>`<option>${esc(s)}</option>`).join('')}</select></div>
<div id="grid" class="test-grid"></div><div class="footer-space"></div>`;
$('#random20').onclick=()=>startRandom();$('#search').oninput=draw;$('#subject').onchange=draw;draw();}
function draw(){const term=$('#search').value.trim().toLowerCase(),sub=$('#subject').value;const list=tests(current).filter(t=>(!sub||t.subject===sub)&&((t.name||'').toLowerCase().includes(term)||(t.subject||'').toLowerCase().includes(term)));$('#grid').innerHTML=list.length?list.map(card).join(''):`<div class="empty" style="grid-column:1/-1"><h3>No tests found</h3><p>Try a different search or subject.</p></div>`;document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>startTest(Number(b.dataset.start)));}
function card(t){const qs=flat(t), answerable=qs.filter(q=>q.answers.length&&q.answers.some(a=>a.correct)).length;return `<div class="card test-card"><div class="tag-row"><span class="tag cyan">${esc(t.subject||sourceInfo[t.source].label)}</span><span class="tag">${qs.length} Q</span></div><h3>${esc(t.name)}</h3><p>${t.time?esc(t.time)+' min • ':''}${answerable} answer-keyed</p><div class="actions"><button class="btn" data-start="${t.id}">Start Test</button></div></div>`}
function startTest(id){const t=DATA.find(x=>Number(x.id)===id);if(!t)return;const qs=flat(t);startQuiz(qs,t.name,t.source,t.id);}
function startRandom(){const pool=tests(current).flatMap(t=>flat(t).filter(q=>q.answers.length&&q.answers.some(a=>a.correct)).map(q=>({...q,testId:t.id,testName:t.name})));shuffle(pool);startQuiz(pool.slice(0,20),'20 Question Random Practice',current,null);}
function startQuiz(qs,title,src,testId){if(!qs.length){alert('No questions are available in this test.');return}quiz={questions:qs,title,source:src,testId,idx:0,selected:{},revealed:{},started:Date.now()};renderQuiz();}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function renderQuiz(){const q=quiz.questions[quiz.idx],total=quiz.questions.length,selected=quiz.selected[q.id],revealed=!!quiz.revealed[q.id];const correct=q.answers.find(a=>a.correct);const canAnswer=q.answers.length>0;$('#quizLayer').classList.remove('hidden');$('#quizLayer').innerHTML=`<div class="quiz-box"><div class="quiz-top"><div><div class="eyebrow">${esc(sourceInfo[quiz.source].label)}</div><div class="quiz-title">${esc(quiz.title)}</div></div><div class="quiz-count">Question ${quiz.idx+1} / ${total}</div></div><div class="bar"><i style="width:${((quiz.idx+1)/total)*100}%"></i></div><div class="q-card"><div class="q-meta">${esc(q.section||'')} ${q.difficulty?'• '+esc(q.difficulty):''} ${q.code?'• '+esc(q.code):''}</div><div class="q-text">${safeHtml(q.text)}${q.image?`<div style="margin-top:14px"><img src="${esc(q.image)}" alt="Question image"></div>`:''}</div><div class="options">${q.answers.map((a,i)=>{let cls='';if(revealed){if(a.correct)cls='correct';else if(selected===a.id)cls='wrong'}else if(selected===a.id)cls='selected';return `<button class="option ${cls}" data-a="${a.id}" ${revealed?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${safeHtml(a.text)}${a.image?`<div><img src="${esc(a.image)}" alt="Answer image"></div>`:''}</span></button>`}).join('')}</div>${!canAnswer?`<div class="notice">Answer key unavailable for this question. It will not be scored.</div>`:''}${revealed?`<div class="notice">${selected===correct?.id?'✓ Correct':'✕ Not correct'}${q.video?` · <a href="${esc(q.video)}" target="_blank" rel="noopener" style="color:var(--cyan)">Open solution video</a>`:''}${q.answers.find(a=>a.id===selected)?.solution?`<div style="margin-top:7px">${safeHtml(q.answers.find(a=>a.id===selected).solution)}</div>`:''}</div>`:''}<div class="quiz-actions"><button class="btn secondary" id="prev" ${quiz.idx===0?'disabled':''}>← Previous</button><div class="right">${selected&&!revealed?`<button class="btn" id="check">Check Answer</button>`:''}${revealed||!canAnswer?`<button class="btn" id="next">${quiz.idx===total-1?'Finish':'Next →'}</button>`:''}</div></div></div></div>`;
$('#quizLayer').querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{quiz.selected[q.id]=Number(b.dataset.a);renderQuiz()});$('#check')?.addEventListener('click',()=>{quiz.revealed[q.id]=true;renderQuiz()});$('#prev').onclick=()=>{if(quiz.idx>0){quiz.idx--;renderQuiz()}};$('#next')?.addEventListener('click',()=>{if(quiz.idx===total-1)finishQuiz();else{quiz.idx++;renderQuiz()}});}
function finishQuiz(){const qs=quiz.questions;let scored=0,correct=0;qs.forEach(q=>{const a=q.answers.find(x=>x.id===quiz.selected[q.id]);const key=q.answers.some(x=>x.correct);if(key){scored++;if(a?.correct)correct++}});const pct=scored?Math.round(correct/scored*100):0;const title=quiz.title;const duration=Math.round((Date.now()-quiz.started)/1000);saveHistory({title,source:quiz.source,testId:quiz.testId,total:qs.length,scored,correct,pct,duration,date:new Date().toISOString()});$('#quizLayer').innerHTML=`<div class="quiz-box"><div class="result"><div class="eyebrow">Test completed</div><div class="result-score">${pct}%</div><h1>${esc(title)}</h1><p><b>${correct}</b> correct out of <b>${scored}</b> scored questions. ${qs.length-scored} question(s) had no usable answer key and were excluded from the score.</p><p>Time: ${Math.floor(duration/60)}m ${String(duration%60).padStart(2,'0')}s</p><div style="display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin-top:22px"><button class="btn" id="again">Try again</button><button class="btn secondary" id="closeQuiz">Back to tests</button></div><div class="review"><h3>Review</h3>${qs.map((q,i)=>{const a=q.answers.find(x=>x.id===quiz.selected[q.id]);const key=q.answers.find(x=>x.correct);const ok=!!a?.correct;return `<div class="review-item ${ok?'good':'bad'}"><b>${i+1}. ${esc(textOf(q.text).slice(0,140))}${textOf(q.text).length>140?'…':''}</b><div style="margin-top:5px;color:#9db1c6">Your answer: ${a?esc(textOf(a.text)):'Not answered'}${key?` • Correct: ${esc(textOf(key.text))}`:''}</div></div>`}).join('')}</div></div></div>`;$('#again').onclick=()=>{if(quiz.testId!=null)startTest(quiz.testId);else startRandom()};$('#closeQuiz').onclick=closeQuiz;}
function saveHistory(item){const key='chaajao_history_v2';const arr=JSON.parse(localStorage.getItem(key)||'[]');arr.unshift(item);localStorage.setItem(key,JSON.stringify(arr.slice(0,100)))}
function closeQuiz(){quiz=null;$('#quizLayer').classList.add('hidden');$('#quizLayer').innerHTML='';}
$('#quizLayer').addEventListener('click',e=>{if(e.target.id==='quizLayer')closeQuiz()});
init();
})();
