const state={data:null,route:{type:"home",subject:null,course:null},search:""};
const app=document.getElementById("app");
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const subjects=()=>state.data.subjects;
const findSubject=id=>subjects().find(s=>slug(s.name)===id);
const findCourse=(s,id)=>s?.courses.find(c=>c.id===id);
const allVideos=()=>subjects().flatMap(s=>s.courses.flatMap(c=>c.videos||[]));
function setRoute(type,subject=null,course=null){state.route={type,subject,course};state.search="";render();window.scrollTo({top:0,behavior:"smooth"})}
function toggleTheme(){document.body.classList.toggle("dark");localStorage.setItem("study-theme",document.body.classList.contains("dark")?"dark":"light");render()}
function layout(content){const dark=document.body.classList.contains("dark");return `<div class="topbar"><div class="topbar-inner"><div class="brand" onclick="setRoute('home')"><div class="logo">SP</div><div><strong>Study Portal</strong><small>25–26 lecture library</small></div></div><div class="search"><span class="icon">⌕</span><input id="search" aria-label="Search" placeholder="Search subjects, chapters, topics or videos…" value="${esc(state.search)}"><span class="kbd">/</span></div><button class="icon-btn" onclick="toggleTheme()" aria-label="Toggle theme">${dark?"☀":"☾"}</button></div></div><main class="container">${content}</main><footer class="footer">Link-only library · Materials intentionally left empty · 26–27 content will be added later.</footer>`}
function home(){const cs=subjects().flatMap(s=>s.courses),v=cs.reduce((n,c)=>n+(c.videos||[]).length,0),active=cs.filter(c=>(c.videos||[]).length).length;return `<section class="hero"><div class="eyebrow">Study library</div><h1>Your lectures, organized in one clean place.</h1><p class="lead">Browse the collected 25–26 lecture links by subject, course, chapter and topic. Open the original video whenever you are ready to study.</p><div class="stats"><div class="stat"><b>${subjects().length}</b> subjects</div><div class="stat"><b>${active}</b> active courses</div><div class="stat"><b>${v}</b> video links</div><div class="stat"><b>25–26</b> active set</div></div></section><div class="section-head"><div><h2>Subjects</h2><div class="count">Choose where you want to study</div></div></div><div class="grid">${subjects().map(s=>{const v=s.courses.reduce((n,c)=>n+(c.videos||[]).length,0);return `<article class="card subject-card" onclick="setRoute('subject','${slug(s.name)}')"><div class="card-top"><div class="subject-icon">${esc(s.name.split(/\s+/).map(x=>x[0]).join("").slice(0,2))}</div><span class="badge ${v?'green':''}">${v?s.courses.filter(c=>(c.videos||[]).length).length+" active":"No links"}</span></div><div><h3>${esc(s.name)}</h3><div class="card-meta"><span>${v} links</span>${v===0?"<span>• coming later</span>":"<span>• open subject →</span>"}</div></div></article>`}).join("")}</div>`}
function subjectPage(s){const active=s.courses.filter(c=>(c.videos||[]).length).length;return `<div class="breadcrumb"><span class="crumb" onclick="setRoute('home')">Home</span><span>›</span><b>${esc(s.name)}</b></div><section class="hero" style="padding-top:0"><div class="eyebrow">Subject</div><h1>${esc(s.name)}</h1><p class="lead">${active} course${active===1?"":"s"} currently have collected video links. Choose a course to open its chapter library.</p></section><div class="course-grid">${s.courses.map(c=>c.empty||!(c.videos||[]).length?`<article class="card course-card empty"><div class="card-top"><h3>${esc(c.name)}</h3><span class="badge">Empty</span></div><p class="count" style="margin-top:12px">No video links collected for this course yet.</p></article>`:`<article class="card course-card" onclick="setRoute('course','${slug(s.name)}','${c.id}')"><div class="card-top"><h3>${esc(c.name)}</h3><span class="badge green">${c.videos.length} links</span></div><div class="card-meta"><span>Chapters: ${new Set(c.videos.map(v=>v.chapter)).size}</span><span>•</span><span>Open library →</span></div></article>`).join("")}</div>`}
function renderVideos(vids){const groups=new Map();for(const v of vids){const key=v.topics?.length?v.topics.join(" · "):"General";if(!groups.has(key))groups.set(key,[]);groups.get(key).push(v)}return [...groups].map(([topic,arr])=>`<div class="topic-group"><div class="topic-title">${esc(topic)}</div><div class="video-list">${arr.map(v=>`<div class="video"><div class="video-info"><div class="video-name">${esc(v.name)}</div>${v.teacher?`<div class="video-topics">${esc(v.teacher)}</div>`:""}</div>${v.youtube?`<a class="watch" href="${esc(v.youtube)}" target="_blank" rel="noopener noreferrer">Watch ↗</a>`:`<span class="badge">No link</span>`}</div>`).join("")}</div></div>`).join("")}
function coursePage(s,c){const map=new Map();for(const v of c.videos){if(!map.has(v.chapter))map.set(v.chapter,[]);map.get(v.chapter).push(v)}const groups=[...map];return `<div class="breadcrumb"><span class="crumb" onclick="setRoute('home')">Home</span><span>›</span><span class="crumb" onclick="setRoute('subject','${slug(s.name)}')">${esc(s.name)}</span><span>›</span><b>${esc(c.name)}</b></div><section class="hero" style="padding-top:0"><div class="eyebrow">Course library</div><h1>${esc(c.name)}</h1><p class="lead">${c.videos.length} collected video links across ${groups.length} chapters. Expand a chapter to see its topics and recordings.</p></section><div class="chapter-list">${groups.map(([chapter,vids],i)=>`<details class="chapter" ${i===0?"open":""}><summary><div><h3>${esc(chapter)}</h3><div class="count">${vids.length} video${vids.length===1?"":"s"}</div></div><span class="chev">⌄</span></summary><div class="chapter-body">${renderVideos(vids)}</div></details>`).join("")}</div>`}
function searchPage(q){const hits=[];for(const s of subjects())for(const c of s.courses)for(const v of c.videos||[]){const hay=[s.name,c.name,v.chapter,v.name,...(v.topics||[]),v.teacher||""].join(" ").toLowerCase();if(hay.includes(q.toLowerCase()))hits.push({s,c,v})}return `<div class="breadcrumb"><span class="crumb" onclick="setRoute('home')">Home</span><span>›</span><b>Search</b></div><section class="hero" style="padding-top:0"><div class="eyebrow">Search</div><h1>Results for “${esc(q)}”</h1><p class="lead">${hits.length} matching video link${hits.length===1?"":"s"}.</p></section><div class="results">${hits.length?hits.map(x=>`<div class="result"><div><b>${esc(x.v.name)}</b><small>${esc(x.s.name)} → ${esc(x.c.name)} → ${esc(x.v.chapter)}</small></div>${x.v.youtube?`<a class="watch" href="${esc(x.v.youtube)}" target="_blank" rel="noopener noreferrer">Watch ↗</a>`:""}</div>`).join(""):`<div class="empty-search">No matching links found.</div>`}</div>`}
function render(){if(!state.data)return;const q=state.search.trim();let content;if(q)content=searchPage(q);else if(state.route.type==="home")content=home();else if(state.route.type==="subject"){const s=findSubject(state.route.subject);content=s?subjectPage(s):home()}else{const s=findSubject(state.route.subject),c=s&&findCourse(s,state.route.course);content=s&&c?coursePage(s,c):home()}app.innerHTML=layout(content);const inp=document.getElementById("search");if(inp){inp.addEventListener("input",e=>{state.search=e.target.value;render();const n=document.getElementById("search");n.focus();n.setSelectionRange(n.value.length,n.value.length)});}}
document.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();document.getElementById("search")?.focus()}});
if(localStorage.getItem("study-theme")==="dark")document.body.classList.add("dark");
fetch("data.json").then(r=>r.json()).then(d=>{state.data=d;render()}).catch(()=>{app.innerHTML="<main class='container'><h1>Could not load the library.</h1><p>Run this folder through a local web server.</p></main>"});
